package:
  name: cptio
  version: "1.0.1"

source:
  path: ..
  # url: https://github.com/kjhall-iri/pycpt/archive/refs/tags/v0.0.1.tar.gz

build:
  number: 0
  string: cptio
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - xarray 

test:
  imports:
    - cptio
    - cptio.utilities
    - cptio.fileio

    

about:
  home: https://github.com/kjhall-iri/
  license: MIT
  summary: 'toolkit bridging the gap between CPT and Xarray' 
  description: 'CPT Xarray Tools & IRI DL Downloads'
  dev_url: https://github.com/kjhall-iri/
