package:
  name: cpttools
  version: "0.2.0"

source:
  path: ../src
  # url: https://github.com/kjhall-iri/pycpt/archive/refs/tags/v0.0.1.tar.gz

build:
  number: 0
  string: cpttools
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - xarray 
    - intake

test:
  imports:
    - cpttools
    - cpttools.utilities
    - cpttools.fileio
    - cpttools.scripts
    - cpttools.datastructures 
    - cpttools.drivers
    

about:
  home: https://github.com/kjhall-iri/
  license: MIT
  summary: 'toolkit bridging the gap between CPT and Xarray' 
  description: 'CPT Xarray Tools & IRI DL Downloads'
  dev_url: https://github.com/kjhall-iri/
