package:
  name: cpttools
  version: "1.0.2"

source:
  path: ../src
  # url: https://github.com/kjhall-iri/pycpt/archive/refs/tags/v0.0.1.tar.gz

build:
  number: 0
  string: cpttools

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - xarray 
    - dask
    - netcdf4
    - intake
    - cftime 
    - pandas 
    - pathlib
    - cartopy
    - matplotlib
    - gitpython
    - pytest

test:
  imports:
    - cpttools
    - cpttools.utilities
    - cpttools.fileio
    - cpttools.datastructures 
    - cpttools.drivers
    

about:
  home: https://github.com/kjhall-iri/
  license: MIT
  summary: 'toolkit bridging the gap between CPT and Xarray' 
  description: 'CPT Xarray Tools & IRI DL Downloads'
  dev_url: https://github.com/kjhall-iri/
